version: '3.8'

services:
  app:
    build:
      context: ./logger
      dockerfile: partial.Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVICE_ENDPOINT: http://modelserving-debugger:8080/api/ingest

  modelserving-debugger:
    build:
      context: .
    ports:
      - "8081:8080"
