apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelserving-debugger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: quay.io/ruimvieira/modelserving-debugger:latest
          ports:
            - containerPort: 8080
